servers:
  web:
    - 91.99.136.140

proxy:
  ssl: true
  hosts:
    - do.submissio.ch
    - www.do.submissio.ch

env:
  secret:
    - RAILS_MASTER_KEY
    - SECRET_KEY_BASE
    - VAPID_PUBLIC_KEY
    - VAPID_PRIVATE_KEY
    - SMTP_USERNAME
    - SMTP_PASSWORD
  clear:
    IS_SUBMISSIO: true
    TENANT_NAME: "submissio"
    MAILER_FROM_ADDRESS: info@submissio.ch

builder:
  arch: x86_64
