service: fizzy
image: pschuez/fizzy

ssh:
  user: root

env:
  clear:
    SMTP_ADDRESS: smtp.postmarkapp.com
    MULTI_TENANT: false
    SOLID_QUEUE_IN_PUMA: true

registry:
  username: pschuez
  password:
    - KAMAL_REGISTRY_PASSWORD

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

volumes:
  - "fizzy_storage:/rails/storage"

asset_path: /rails/public/assets
