service: fizzy
image: pschuez/fizzy

ssh:
  user: root

env:
  secret:
    - RAILS_MASTER_KEY
    - SECRET_KEY_BASE
    - VAPID_PUBLIC_KEY
    - VAPID_PRIVATE_KEY
    - SMTP_USERNAME
    - SMTP_PASSWORD
  clear:
    MAILER_FROM_ADDRESS: hey@margareti.com # The email "from" address that Fizzy sends email from
    SMTP_ADDRESS: smtp.postmarkapp.com # The SMTP server you'll use to send email
    MULTI_TENANT: false # Set to false to enable single-tenant mode
    SOLID_QUEUE_IN_PUMA: true # Run background jobs in the app container

registry:
  username: pschuez
  password:
    - KAMAL_REGISTRY_PASSWORD

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

volumes:
  - "fizzy_storage:/rails/storage"

asset_path: /rails/public/assets
