production: &production
  auto_close_all_due:
    class: Card::AutoCloseAllDueJob
    schedule: every hour
  auto_reconsider_all_inactive:
    class: Card::AutoReconsiderAllStagnatedJob
    schedule: every hour
  remove_abandoned_creations:
    class: RemoveAbandonedCreationsJob
    schedule: every hour
  sqlite_backups:
    class: SQLiteBackupsJob
    schedule: every day at 05:00
  delete_unused_tags:
    class: DeleteUnusedTagsJob
    schedule: every day at 04:00
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12

beta: *production
staging: *production
