name: CI (SaaS)

on:
  push:

permissions:
  contents: read

jobs:
  test_oss:
    name: Test (OSS)
    uses: ./.github/workflows/test.yml
    with:
      saas: false
  test_saas:
    name: Test (SaaS)
    uses: ./.github/workflows/test.yml
    with:
      saas: true
    secrets:
      FIZZY_GH_TOKEN: ${{ secrets.FIZZY_GH_TOKEN }}
